### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by mofeing** [bsc-quantic/rosnet#33]
It would be nice to have a logo if we plan to expand our userbase. I don't have a clear idea in mind but we could find inspiration in the rosnet | tensor symmetry.

**Comment by eletrogui** [comment]
Can I help with the logo?
If so,
What colors do you prefer?
What elements?

**Comment by mofeing** [comment]
hi @guilherme-svg 
thanks for the offer but this is mostly a reminder for the future and requires consensus by all the team
